version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r deployment_package.zip .
  post_build:
    commands:
      - echo "Updating Lambda Function..."
      - aws lambda update-function-code --function-name aboutMe --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
